name: Deploy DigitalBite to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e
            echo "1. Navegando a la carpeta /var/www/digitalbite-app..."
            cd /var/www/digitalbite-app
            
            echo "2. Forzando actualización de la última versión de GitHub..."
            git fetch --all
            git reset --hard origin/main
            
            echo "3. Instalando dependencias..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm install --legacy-peer-deps
            
            echo "4. Construyendo proyecto para producción..."
            npm run build
            
            echo "5. Reiniciando procesos con PM2..."
            pm2 restart all || pm2 start npm --name "digitalbite" -- start
            echo "¡Despliegue completado!"
