name: Deploy DigitalBite to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            set -e
            echo "1. Navegando a la carpeta /var/www/digitalbite-app..."
            cd /var/www/digitalbite-app
            
            echo "2. Verificando repositorio Git..."
            if [ ! -d ".git" ]; then
              echo "Carpeta no es un repositorio. Inicializando..."
              git init
              git remote add origin https://github.com/diemoroy-ss/digitalbite.git
            else
              echo "Repositorio Git detectado."
            fi
            
            echo "3. Forzando actualización de la última versión de GitHub..."
            git fetch --all
            git reset --hard origin/main
            
            echo "3. Instalando dependencias..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm install --legacy-peer-deps
            
            echo "4. Limpiando archivos de bloqueo de builds anteriores..."
            rm -f .next/lock || true
            
            echo "5. Construyendo proyecto para producción..."
            npm run build
            
            echo "5. Reiniciando procesos con PM2..."
            pm2 restart all || pm2 start npm --name "digitalbite" -- start
            echo "¡Despliegue completado!"
